shopware:
    admin_worker:
        enable_admin_worker: false
    auto_update:
        enabled: false

framework:
    cache:
        default_redis_provider: 'redis://localhost:6379'
        app: cache.adapter.redis
