#override defaults for dev
version: "3.7"

services:

  nginx:
    image: nginx
    ports:
      - "80:8000"
    environment:
      - NGINX_HOST=rafu.de.localhost
      - NGINX_PORT=80
    links:
      - app
    volumes:
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/

  app:
    build: .
    depends_on:
      - mysql
      - elasticsearch
    environment:
      - APP_DEBUG=1
      - APP_URL=http://rafu.de.localhost
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=1
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=1
      - SHOPWARE_ES_INDEX_PREFIX=sw
      - SHOPWARE_CDN_STRATEGY_DEFAULT=id
      - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    volumes:
      - ./config/etc/php8/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./config/etc/php8/php-fpm.d/fpm-pool.conf:/usr/local/etc/php/php-fpm.d/fpm-pool.conf:ro
      - ./:/var/www/
    links:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    environment:
      - MYSQL_ROOT_PASSWORD=shopware
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: elastic/elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node


volumes:
  db-data:
